// <auto-generated />
using System;
using Aives.Domain.Enums;
using Aives.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aives.Infrastructure.Migrations
{
    [DbContext(typeof(AivesDbContext))]
    [Migration("20261008172917_AddSessionCodeAndMonitoringFields")]
    partial class AddSessionCodeAndMonitoringFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "doc_type", new[] { "CONTENT", "LEARNING_OUTCOMES" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "exam_status", new[] { "DRAFT", "SCHEDULED", "OPEN", "CLOSED", "CANCELLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_status", new[] { "NOT_STARTED", "IN_PROGRESS", "COMPLETED", "CANCELLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "submission_status", new[] { "PENDING_REVIEW", "SUBMITTED", "REVIEWED", "PUBLISHED", "CANCELLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "ADMIN", "TEACHER", "STUDENT" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aives.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("answer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text")
                        .HasColumnName("ai_feedback");

                    b.Property<float?>("AiScore")
                        .HasColumnType("real")
                        .HasColumnName("ai_score");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<float?>("FinalScore")
                        .HasColumnType("real")
                        .HasColumnName("final_score");

                    b.Property<bool?>("IsFollowUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_follow_up");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("ResultId")
                        .HasColumnType("integer")
                        .HasColumnName("result_id");

                    b.Property<string>("StudentAnswer")
                        .HasColumnType("text")
                        .HasColumnName("student_answer");

                    b.Property<string>("TeacherComment")
                        .HasColumnType("text")
                        .HasColumnName("teacher_comment");

                    b.Property<string>("Transcript")
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.HasKey("AnswerId")
                        .HasName("answers_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "ResultId" }, "idx_answers_result");

                    b.HasIndex(new[] { "ResultId", "QuestionId" }, "unique_result_question")
                        .IsUnique();

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("course_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.HasKey("CourseId")
                        .HasName("courses_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "CourseCode" }, "courses_course_code_key")
                        .IsUnique();

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId")
                        .HasName("enrollments_pkey");

                    b.HasIndex(new[] { "CourseId" }, "idx_enrollments_course");

                    b.HasIndex(new[] { "StudentId" }, "idx_enrollments_student");

                    b.HasIndex(new[] { "StudentId", "CourseId" }, "unique_student_course")
                        .IsUnique();

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ExamId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exam_code");

                    b.Property<ExamStatus?>("ExamStatus")
                        .HasColumnType("exam_status")
                        .HasColumnName("exam_status");

                    b.Property<int>("MaxQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_questions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("ExamId")
                        .HasName("exams_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "ExamCode" }, "exams_exam_code_key")
                        .IsUnique();

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<float>("QuestionScore")
                        .HasColumnType("real")
                        .HasColumnName("question_score");

                    b.HasKey("ExamId", "QuestionId")
                        .HasName("exam_questions_pkey");

                    b.HasIndex("QuestionId");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.ExamSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentEnrollment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_enrollment");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<int>("MaxCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("max_capacity");

                    b.Property<string>("Room")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("room");

                    b.Property<int>("ScheduledBy")
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_by");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("session_code");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("session_name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<SessionStatus?>("Status")
                        .HasColumnType("session_status")
                        .HasColumnName("status");

                    b.HasKey("SessionId")
                        .HasName("exam_sessions_pkey");

                    b.HasIndex("ExamId");

                    b.HasIndex("ScheduledBy");

                    b.HasIndex(new[] { "SessionCode" }, "exam_sessions_session_code_key")
                        .IsUnique();

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.MarkdownDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DocType>("DocType")
                        .HasColumnType("doc_type")
                        .HasColumnName("doc_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.HasKey("DocumentId")
                        .HasName("markdown_documents_pkey");

                    b.HasIndex("UploadedBy");

                    b.HasIndex(new[] { "CourseId" }, "idx_markdown_documents_course");

                    b.ToTable("markdown_documents", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.QuestionBank", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<bool?>("IsFollowUpAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_follow_up_allowed");

                    b.Property<float?>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasColumnName("max_score")
                        .HasDefaultValueSql("1.0");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("SampleAnswer")
                        .HasColumnType("text")
                        .HasColumnName("sample_answer");

                    b.HasKey("QuestionId")
                        .HasName("question_bank_pkey");

                    b.HasIndex("DocumentId");

                    b.HasIndex(new[] { "CourseId" }, "idx_question_bank_course");

                    b.ToTable("question_bank", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("result_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ResultId"));

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text")
                        .HasColumnName("ai_feedback");

                    b.Property<float?>("AiScore")
                        .HasColumnType("real")
                        .HasColumnName("ai_score");

                    b.Property<string>("FinalFeedback")
                        .HasColumnType("text")
                        .HasColumnName("final_feedback");

                    b.Property<float?>("FinalScore")
                        .HasColumnType("real")
                        .HasColumnName("final_score");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<SubmissionStatus?>("Status")
                        .HasColumnType("submission_status")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ResultId")
                        .HasName("results_pkey");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "SessionId" }, "idx_results_session");

                    b.HasIndex(new[] { "StudentId" }, "idx_results_student");

                    b.HasIndex(new[] { "StudentId", "SessionId" }, "unique_result_student_session")
                        .IsUnique();

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.SessionEnrollment", b =>
                {
                    b.Property<int>("SessionEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("session_enrollment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("SessionEnrollmentId"));

                    b.Property<int?>("CurrentQuestionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_question_index");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<SessionStatus?>("Status")
                        .HasColumnType("session_status")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("SessionEnrollmentId")
                        .HasName("session_enrollments_pkey");

                    b.HasIndex(new[] { "SessionId" }, "idx_session_enrollments_session");

                    b.HasIndex(new[] { "StudentId" }, "idx_session_enrollments_student");

                    b.HasIndex(new[] { "StudentId", "SessionId" }, "unique_student_session")
                        .IsUnique();

                    b.ToTable("session_enrollments", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Aives.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Aives.Domain.Entities.QuestionBank", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("answers_question_id_fkey");

                    b.HasOne("Aives.Domain.Entities.Result", "Result")
                        .WithMany("Answers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("answers_result_id_fkey");

                    b.Navigation("Question");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Aives.Domain.Entities.Course", b =>
                {
                    b.HasOne("Aives.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("CourseCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("courses_created_by_fkey");

                    b.HasOne("Aives.Domain.Entities.User", "Teacher")
                        .WithMany("CourseTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("courses_teacher_id_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Aives.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Aives.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("enrollments_course_id_fkey");

                    b.HasOne("Aives.Domain.Entities.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("enrollments_student_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Aives.Domain.Entities.Exam", b =>
                {
                    b.HasOne("Aives.Domain.Entities.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exams_course_id_fkey");

                    b.HasOne("Aives.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exams_created_by_fkey");

                    b.Navigation("Course");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Aives.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("Aives.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_questions_exam_id_fkey");

                    b.HasOne("Aives.Domain.Entities.QuestionBank", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_questions_question_id_fkey");

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Aives.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("Aives.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamSessions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_sessions_exam_id_fkey");

                    b.HasOne("Aives.Domain.Entities.User", "ScheduledByNavigation")
                        .WithMany("ExamSessions")
                        .HasForeignKey("ScheduledBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exam_sessions_scheduled_by_fkey");

                    b.Navigation("Exam");

                    b.Navigation("ScheduledByNavigation");
                });

            modelBuilder.Entity("Aives.Domain.Entities.MarkdownDocument", b =>
                {
                    b.HasOne("Aives.Domain.Entities.Course", "Course")
                        .WithMany("MarkdownDocuments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("markdown_documents_course_id_fkey");

                    b.HasOne("Aives.Domain.Entities.User", "UploadedByNavigation")
                        .WithMany("MarkdownDocuments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("markdown_documents_uploaded_by_fkey");

                    b.Navigation("Course");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("Aives.Domain.Entities.QuestionBank", b =>
                {
                    b.HasOne("Aives.Domain.Entities.Course", "Course")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("question_bank_course_id_fkey");

                    b.HasOne("Aives.Domain.Entities.MarkdownDocument", "Document")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("question_bank_document_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Aives.Domain.Entities.Result", b =>
                {
                    b.HasOne("Aives.Domain.Entities.User", "ReviewedByNavigation")
                        .WithMany("ResultReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("results_reviewed_by_fkey");

                    b.HasOne("Aives.Domain.Entities.ExamSession", "Session")
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("results_session_id_fkey");

                    b.HasOne("Aives.Domain.Entities.User", "Student")
                        .WithMany("ResultStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("results_student_id_fkey");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Aives.Domain.Entities.SessionEnrollment", b =>
                {
                    b.HasOne("Aives.Domain.Entities.ExamSession", "Session")
                        .WithMany("SessionEnrollments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("session_enrollments_session_id_fkey");

                    b.HasOne("Aives.Domain.Entities.User", "Student")
                        .WithMany("SessionEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("session_enrollments_student_id_fkey");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Aives.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Exams");

                    b.Navigation("MarkdownDocuments");

                    b.Navigation("QuestionBanks");
                });

            modelBuilder.Entity("Aives.Domain.Entities.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamSessions");
                });

            modelBuilder.Entity("Aives.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("SessionEnrollments");
                });

            modelBuilder.Entity("Aives.Domain.Entities.MarkdownDocument", b =>
                {
                    b.Navigation("QuestionBanks");
                });

            modelBuilder.Entity("Aives.Domain.Entities.QuestionBank", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("Aives.Domain.Entities.Result", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Aives.Domain.Entities.User", b =>
                {
                    b.Navigation("CourseCreatedByNavigations");

                    b.Navigation("CourseTeachers");

                    b.Navigation("Enrollments");

                    b.Navigation("ExamSessions");

                    b.Navigation("Exams");

                    b.Navigation("MarkdownDocuments");

                    b.Navigation("ResultReviewedByNavigations");

                    b.Navigation("ResultStudents");

                    b.Navigation("SessionEnrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
